/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.Principal;

import vista.articulosPanel.ArticulosPanel;
import vista.articulosPanel.ArticulosPanel.ArticulosPanelDelegate;
import vista.clientesPanel.ClientesPanel;
import vista.clientesPanel.ClientesPanel.ClientesPanelDelegates;
import java.util.Map;
import conexion.MySQLClass;
import vista.ventaPanel.VentaPanel;
import vista.ventaPanel.VentaPanel.VentaPanelDelegate;
import vista.ventaPanel.controlador.VentaPanelController;

/**
 *
 * @author Noe
 */
public class PrincipalView extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */

    ClientesPanel clientesPanelIns;
    VentaPanel ventaPanelIns;
    
    
    public PrincipalView() {
        
        initComponents();
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipalTbp = new javax.swing.JTabbedPane();
        principalTab1Pnl = new javax.swing.JPanel();
        principalTab2Pnl = new javax.swing.JPanel();
        principarlTab3Pnl = new javax.swing.JPanel();
        principalTabAlmacenesPnl = new javax.swing.JPanel();
        principalTabMovExistPnl = new javax.swing.JPanel();
        principalTabResultadosPnl = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);

        panelPrincipalTbp.setPreferredSize(new java.awt.Dimension(1200, 696));

        javax.swing.GroupLayout principalTab1PnlLayout = new javax.swing.GroupLayout(principalTab1Pnl);
        principalTab1Pnl.setLayout(principalTab1PnlLayout);
        principalTab1PnlLayout.setHorizontalGroup(
            principalTab1PnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1029, Short.MAX_VALUE)
        );
        principalTab1PnlLayout.setVerticalGroup(
            principalTab1PnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );

        panelPrincipalTbp.addTab("Venta", principalTab1Pnl);

        javax.swing.GroupLayout principalTab2PnlLayout = new javax.swing.GroupLayout(principalTab2Pnl);
        principalTab2Pnl.setLayout(principalTab2PnlLayout);
        principalTab2PnlLayout.setHorizontalGroup(
            principalTab2PnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1029, Short.MAX_VALUE)
        );
        principalTab2PnlLayout.setVerticalGroup(
            principalTab2PnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );

        panelPrincipalTbp.addTab("Alta clientes", principalTab2Pnl);

        javax.swing.GroupLayout principarlTab3PnlLayout = new javax.swing.GroupLayout(principarlTab3Pnl);
        principarlTab3Pnl.setLayout(principarlTab3PnlLayout);
        principarlTab3PnlLayout.setHorizontalGroup(
            principarlTab3PnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1029, Short.MAX_VALUE)
        );
        principarlTab3PnlLayout.setVerticalGroup(
            principarlTab3PnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );

        panelPrincipalTbp.addTab("Articulos", principarlTab3Pnl);

        javax.swing.GroupLayout principalTabAlmacenesPnlLayout = new javax.swing.GroupLayout(principalTabAlmacenesPnl);
        principalTabAlmacenesPnl.setLayout(principalTabAlmacenesPnlLayout);
        principalTabAlmacenesPnlLayout.setHorizontalGroup(
            principalTabAlmacenesPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1029, Short.MAX_VALUE)
        );
        principalTabAlmacenesPnlLayout.setVerticalGroup(
            principalTabAlmacenesPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );

        panelPrincipalTbp.addTab("Almacenes", principalTabAlmacenesPnl);

        javax.swing.GroupLayout principalTabMovExistPnlLayout = new javax.swing.GroupLayout(principalTabMovExistPnl);
        principalTabMovExistPnl.setLayout(principalTabMovExistPnlLayout);
        principalTabMovExistPnlLayout.setHorizontalGroup(
            principalTabMovExistPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1029, Short.MAX_VALUE)
        );
        principalTabMovExistPnlLayout.setVerticalGroup(
            principalTabMovExistPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );

        panelPrincipalTbp.addTab("Movimiento de existencias", principalTabMovExistPnl);

        javax.swing.GroupLayout principalTabResultadosPnlLayout = new javax.swing.GroupLayout(principalTabResultadosPnl);
        principalTabResultadosPnl.setLayout(principalTabResultadosPnlLayout);
        principalTabResultadosPnlLayout.setHorizontalGroup(
            principalTabResultadosPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1029, Short.MAX_VALUE)
        );
        principalTabResultadosPnlLayout.setVerticalGroup(
            principalTabResultadosPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );

        panelPrincipalTbp.addTab("Resultados", principalTabResultadosPnl);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelPrincipalTbp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelPrincipalTbp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTabbedPane panelPrincipalTbp;
    public javax.swing.JPanel principalTab1Pnl;
    public javax.swing.JPanel principalTab2Pnl;
    public javax.swing.JPanel principalTabAlmacenesPnl;
    public javax.swing.JPanel principalTabMovExistPnl;
    public javax.swing.JPanel principalTabResultadosPnl;
    public javax.swing.JPanel principarlTab3Pnl;
    // End of variables declaration//GEN-END:variables

}
