/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Noe
 */
public class ResultadosView extends javax.swing.JPanel {

    /**
     * Creates new form ResultadosView
     */
    public ResultadosView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        totalInvenSinGanLbl = new javax.swing.JLabel();
        totalInvConGanLbl = new javax.swing.JLabel();
        totalVendidoConDeudLbl = new javax.swing.JLabel();
        totalRecibidoLbl = new javax.swing.JLabel();
        totalDeudasLbl = new javax.swing.JLabel();
        gananciaEsperadaLbl = new javax.swing.JLabel();
        gananciaActualLbl = new javax.swing.JLabel();
        gananciaYRecLbl = new javax.swing.JLabel();
        totalEntradasLbl = new javax.swing.JLabel();
        refrescarBtn = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder("    Resultados"));

        totalInvenSinGanLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        totalInvenSinGanLbl.setText("Total en inventario sin ganancia:");
        totalInvenSinGanLbl.setToolTipText("Todo lo que hay invertido en el inventario actual sin contar la ganancia");

        totalInvConGanLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        totalInvConGanLbl.setText("Total en inventario con ganancia:");
        totalInvConGanLbl.setToolTipText("todo lo que hay invertido en el inventario actual contando la ganancia");

        totalVendidoConDeudLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        totalVendidoConDeudLbl.setText("Total vendido con deudas:");
        totalVendidoConDeudLbl.setToolTipText("Todo lo vendido contando las deudas osea si todos pagan este seria el total de dinero recibido");

        totalRecibidoLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        totalRecibidoLbl.setText("Total recibido:");
        totalRecibidoLbl.setToolTipText("la suma de todos los pagos");

        totalDeudasLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        totalDeudasLbl.setText("Total de deudas:");
        totalDeudasLbl.setToolTipText("La suma de todas las deudas ");

        gananciaEsperadaLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        gananciaEsperadaLbl.setText("Ganancia esperada:");
        gananciaEsperadaLbl.setToolTipText("Ganancia que se tiene esperada si todos pagan");

        gananciaActualLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        gananciaActualLbl.setText("Ganancia actual:");
        gananciaActualLbl.setToolTipText("La gancia actualmente");

        gananciaYRecLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        gananciaYRecLbl.setText("Suma pagos - montoTotal:");

        totalEntradasLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        totalEntradasLbl.setText("Total de entradas:");
        totalEntradasLbl.setToolTipText("Todo lo que ha entrado, se puede decir que es la invercion total");

        refrescarBtn.setText("Refrescar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(totalInvenSinGanLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(totalInvConGanLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 718, Short.MAX_VALUE)
                    .addComponent(totalVendidoConDeudLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(totalRecibidoLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(totalDeudasLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(gananciaEsperadaLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(gananciaActualLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(gananciaYRecLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(totalEntradasLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(refrescarBtn)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(refrescarBtn)
                .addGap(8, 8, 8)
                .addComponent(totalEntradasLbl)
                .addGap(18, 18, 18)
                .addComponent(totalInvenSinGanLbl)
                .addGap(18, 18, 18)
                .addComponent(totalInvConGanLbl)
                .addGap(57, 57, 57)
                .addComponent(totalVendidoConDeudLbl)
                .addGap(18, 18, 18)
                .addComponent(totalRecibidoLbl)
                .addGap(18, 18, 18)
                .addComponent(totalDeudasLbl)
                .addGap(18, 18, 18)
                .addComponent(gananciaEsperadaLbl)
                .addGap(18, 18, 18)
                .addComponent(gananciaActualLbl)
                .addGap(18, 18, 18)
                .addComponent(gananciaYRecLbl)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel gananciaActualLbl;
    public javax.swing.JLabel gananciaEsperadaLbl;
    public javax.swing.JLabel gananciaYRecLbl;
    public javax.swing.JButton refrescarBtn;
    public javax.swing.JLabel totalDeudasLbl;
    public javax.swing.JLabel totalEntradasLbl;
    public javax.swing.JLabel totalInvConGanLbl;
    public javax.swing.JLabel totalInvenSinGanLbl;
    public javax.swing.JLabel totalRecibidoLbl;
    public javax.swing.JLabel totalVendidoConDeudLbl;
    // End of variables declaration//GEN-END:variables
}
