/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.clientesPanel.vista;

/**
 *
 * @author Noe
 */
public class ClientesPanelView extends javax.swing.JPanel {

    /**
     * Creates new form ClientesPanel
     */
    public ClientesPanelView() {
        
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        clientesJtb = new javax.swing.JTable();
        nombreJtf = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder("    Clientes"));

        clientesJtb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "nombre", "apellidos"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        clientesJtb.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        clientesJtb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                clientesJtbMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(clientesJtb);

        nombreJtf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nombreJtfKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nombreJtfKeyTyped(evt);
            }
        });

        jLabel1.setText("Nombe:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nombreJtf, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreJtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nombreJtfKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreJtfKeyReleased
        // TODO add your handling code here:
        //buscarClienteWithNombre(nombreJtf.getText());
    }//GEN-LAST:event_nombreJtfKeyReleased
    
    private void nombreJtfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreJtfKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreJtfKeyTyped
    
    private void clientesJtbMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clientesJtbMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_clientesJtbMousePressed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTable clientesJtb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextField nombreJtf;
    // End of variables declaration//GEN-END:variables
}
